name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint
      run: ruff check .
    - name: Tests
      run: PYTHONPATH=. pytest -q